name: code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Start code server
      run: docker run -d --name code -p 9000:9000 chinodesuuu/coder:ubuntu
    - name: Git clone
      run: docker exec code git clone $REPO
      env:
        REPO: https://github.com/${{ github.repository }}.git ~/projects
    - name: Download ngrok
      run: wget $(curl -s https://ngrok.com/download | grep -o "https://.*linux-amd64.zip") -O ../ngrok.zip
    - name: Unzip ngrok
      run: unzip ../ngrok.zip -d ..
    - name: Setup ngrok
      run: ../ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }} 
    - name: Start ngrok forwarding
      run: ../ngrok http 9000 --region ap --log "stdout"
