name: code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Start code server
      run: docker run -d --name code -p 9000:9000 -v $PWD:/home/coder/projects chinodesuuu/coder:ubuntu
    - name: Start ssh forwarding
      run: ssh -R 80:localhost:9000 ssh.localhost.run
